name: Go

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./... -covermode=count -coverprofile="coverage.out"

    - name: Bench cowmaps
      working-directory: ./cowmaps
      run: go test . -bench . -benchmem

    - name: Bench cowslices
      working-directory: ./cowslices
      run: go test . -bench . -benchmem

    - name: Bench romaps
      working-directory: ./romaps
      run: go test . -bench . -benchmem

    - name: Bench roslices
      working-directory: ./roslices
      run: go test . -bench . -benchmem

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v2

    - name: Test Submodule
      working-directory: ./test
      run: go test -v ./...
